name: ci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

env:
  RETAILCRM_URL: ${{ secrets.RETAILCRM_URL }}
  RETAILCRM_KEY: ${{ secrets.RETAILCRM_KEY }}
  RETAILCRM_VERSION: ${{ secrets.RETAILCRM_VERSION }}
  RETAILCRM_SITE: ${{ secrets.RETAILCRM_SITE }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.0', '7.1', '7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: pcov.directory=lib
          coverage: pcov
      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ env.HOME }}/.composer/cache
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        run: composer install -o
      - name: Run tests
        run: php ./vendor/phpunit/phpunit/phpunit -c phpunit.xml.dist
      - name: Coverage
        run: bash <(curl -s https://codecov.io/bash)
